site_name: アドバリーシステム ドキュメントページ
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon:  material/toggle-switch-off-outline
        name: ダークテーマに切り替える
      primary: black
      accent: lime
    - scheme: slate
      toggle:
        primary: black
        icon: material/toggle-switch
        name: ライトテーマに切り替える
      primary: black
      accent: lime
  logo: img/logo.png
  favicon: img/favicon.ico
  language: ja
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.top

extra:
  social:
    - icon: fontawesome/solid/home
      link: https://advaly.co.jp
      name: Official Website
    - icon: fontawesome/brands/github
      link: https://github.com/advaly
      name: Advaly System on Github
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ADVALY
      name: Advaly System on Facebook
    - icon: fontawesome/brands/line
      link: https://lin.ee/7o4E0Xt
      name: Advaly System on LINE

extra_css:
  - css/custom.css

use_directory_urls: false
