site_name: アドバリーシステム ドキュメントページ
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon:  material/toggle-switch-off-outline
        name: ダークテーマに切り替える
      primary: black
      accent: lime
    - scheme: slate
      toggle:
        primary: black
        icon: material/toggle-switch
        name: ライトテーマに切り替える
      primary: black
      accent: lime
  logo: img/logo.png
  favicon: img/favicon.ico
  language: ja
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.top

extra_css:
  - css/custom.css

use_directory_urls: false
